### ISSUE TITLE
Running fig command in debug mode generates error

### ISSUE THREAD

**Issue by matsuobasho** [felixludos/omni-fig#4]
This is probably a question for the repo that uses this command, but maybe you can help, since I'm totally new to fig.

I'm running the command
`fig generate demo`

as per the instructions on this [Readme](https://github.com/causalNLP/cladder).

I've installed the dependencies and this command executes.  However, I'm trying to run this in debug mode in order to step through the code.

When I run
`fig generate -d demo`

I get an error:
`AssertionError: not all files exist`

Is the execution and error handling in debug mode different from the regular mode?

**Comment by felixludos** [comment]
It sounds like debug mode is probably not what you want. Using debug mode in omni-fig (i.e. including `-d`) automatically prepends the `debug.yml` as config file - which may override various settings and even the actual entry point (i.e. script that gets run). In this case, I'm guessing the contents of `config/debug.yml` sets a different script name (i.e. `_meta.script_name`) than `generate`, and thus you end up somewhere totally different.

If you need to use a debugger to step through the code at runtime, then you would have run the command through an IDE (e.g. Pycharm). FYI what the `fig` command actually does is call [`omnifig.entry()`](https://omnifig.readthedocs.io/en/latest/project-structure/cli.html#:~:text=the%20fig%20command%20really%20just%20calls%20fig.entry()). So you can also turn that into any regular python script and use any standard debugger.

However, your confusion is quite warranted, so I'll change the name of the debug mode in a future version (since debug mode isn't related to a debugger or stepping through the code at all).

**Comment by matsuobasho** [comment]
Thanks for the insights.  So the repo actually has a `main.py` file with `omnifig.entry()`.

When I run it in debug mode in VSCode, it then steps into this `__init__.py`:
```
__version__ = '0.1'

from .graphs import create_graph
from .queries import create_query
from .verbal import load_story
from . import formatting
from . import verbal
from . import util
from . import generator
```

After which I get an error:
`
Exception has occurred: GeneralProject.NoScriptError
exception: no description
  File "C:\Users\Bob\cladder\main.py", line 4, in <module>
    fig.entry()
omnifig.organization.workspaces.GeneralProject.NoScriptError: 
`

**Comment by matsuobasho** [comment]
Hi @felixludos , can you give a pointer on my question above.  Thanks so much!

**Comment by felixludos** [comment]
I'm guessing you're not specifying any (registered) script to run. If you want to hardcode the `main.py` to run a specific script (e.g. `generate`) then you need to specify it like so: `omnifig.entry("generate")` (see [docs](https://omnifig.readthedocs.io/en/latest/project-structure/cli.html#:~:text=another%20python%20file-,launch.py,-that%20looks%20like)). Otherwise, you have to specify what script in the command (e.g. `python main.py generate`) (see [docs](https://omnifig.readthedocs.io/en/latest/project-structure/cli.html#:~:text=python%20main.py%20%3Cscript%3E)). Also, don't forget to specify any config files in the command (e.g. `demo`).

**Comment by matsuobasho** [comment]
Thanks!  So I think it would be something like this:
`python main.py generate <config_files>`

The problem is that the Cladder repo has lots of different config files, so which one would I specify?:
https://github.com/causalNLP/cladder/tree/main/config

Btw, I had opened an issue on CLadder since I can't run the example there (I just saw that you're one of the 2 contributors:
https://github.com/causalNLP/cladder/issues/3

**Comment by felixludos** [comment]
It depends on what do you want to do? If it's just run the demo, then you only need to specify the `demo` config (just like when running `fig generate demo`).
PS: as for CLadder, I'm currently working on an extension, including CLadderV2, which includes quite a bit of refactoring - so maintaining the old stuff has unfortunately become a lower priority - sorry.

**Comment by matsuobasho** [comment]
I want to be able to to run main.py.  Currently, even without debug mode, it errors out.  

```python
Exception has occurred: GeneralProject.NoScriptError
exception: no description
  File "C:\Users\Bob\cladder\main.py", line 4, in <module>
    fig.entry()
omnifig.organization.workspaces.GeneralProject.NoScriptError:
```

I want to go through what the CLadder paper did and it's impossible to currently reproduce the work.

**Comment by felixludos** [comment]
`main.py` doesn't do anything on its own - it's just an entry point to run any of the scripts. For example, to run the generation demo using `main.py` you can use the command `python main.py generate demo` (which is equivalent to `fig generate demo`, as discussed in the omnifig docs linked above).

**Comment by matsuobasho** [comment]
Great, that helps a lot, thanks!
